# Constantes Menú Principal
GESTION_PACIENTES = 1
OPERACIONES_PACIENTES = 2
GESTION_HOSPITALES = 3
GESTION_DIAGNOSTICOS = 4
SALIR = 5

# Constantes Menú Gestion Pacientes
AGREGAR_PACIENTE = 1
ELIMINAR_PACIENTE = 2
OBTENER_PACIENTE = 3
ACTUALIZAR_PACIENTE = 4
VOLVER_MENU_PRINCIPAL = 5

# Constantes Menú Operaciones Pacientes
BUSCAR_PACIENTE_RANGO_DNI = 1
BUSCAR_PACIENTE_ENFERMEDAD = 2
BUSCAR_PACIENTE_MEDICAMENTO = 3
LISTAR_PACIENTES = 4

# Constantes Actualizar Paciente
ACTUALIZAR_NOMBRE = 1
ACTUALIZAR_FECHA_NACIMIENTO = 2
ACTUALIZAR_HISTORIAL_ENFERMEDADES = 3
ACTUALIZAR_MEDICAMENTOS = 4

# Constantes Menú Gestion Hospitales
AGREGAR_HOSPITAL = 1
AGREGAR_CONEXION = 2
BUSCAR_RUTA = 3
BUSCAR_RUTA_CORTA = 4
CALCULAR_DISTANCIAS = 5
VOLVER_MENU_HOSPITALES = 6

# Constantes Menú Gestion Diagnósticos
ENCONTRAR_PASOS = 1
OPERACIONES_DIAGNOSTICOS = 2
VOLVER_MENU_PRINCIPAL_DIAGNOSTICOS = 3

# Operaciones Diagnósticos
AGREGAR_DIAGNOSTICO = 1
MODIFICAR_DIAGNOSTICO = 2
ELIMINAR_DIAGNOSTICO = 3
BUSCAR_DIAGNOSTICO_SINTOMA = 4
GENERAR_REPORTE = 5
VOLVER_MENU_DIAGNOSTICOS = 6